# Ensure that python-apt is installed on a debian/ubuntu machine
- name: Ensure that package cache is updated
  action: shell apt-get update -y
  when: is_debian_or_ubuntu
  sudo: yes
  sudo_user: root
  environment:
    http_proxy: http://cloud-proxy:3128
    https_proxy: http://cloud-proxy:3128

- name: apt update
  apt: update_cache=yes
  remote_user: ubuntu
  sudo: yes
  sudo_user: root
  when: is_debian_or_ubuntu
  environment:
    http_proxy: http://cloud-proxy:3128
    https_proxy: http://cloud-proxy:3128

- name: apt upgrade
  apt: upgrade=full
  remote_user: ubuntu
  sudo: yes
  sudo_user: root
  when: is_debian_or_ubuntu
  environment:
    http_proxy: http://cloud-proxy:3128
    https_proxy: http://cloud-proxy:3128

- name: test is reboot requested
  stat: path=/var/run/reboot-required
  when: is_debian_or_ubuntu
  register: deb_reboot

- name: restart
  command: shutdown -r now "Ansible updates triggered"
  remote_user: ubuntu
  sudo: yes
  sudo_user: root
  async: 0
  poll: 0
  ignore_errors: true
  when: deb_reboot.stat.exists

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=1
  sudo: false
  when: deb_reboot.stat.exists
  
- name: Check if `python-apt` package is installed
  action: shell apt-get install -y {{item}}
  with_items:
    - python-apt
    - sysvinit-utils
    - software-properties-common
    - python-software-properties
    - python-pycurl
    - htop
    - most
    - s3cmd
    - iptraf
    - vim
    - emacs
    - git
  when: is_debian_or_ubuntu
  environment:
    http_proxy: http://cloud-proxy:3128
    https_proxy: http://cloud-proxy:3128

- name: Ensure extra reposistories are present (Ubuntu)
  action: apt_repository repo="deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} universe multiverse" state=present
  when: is_ubuntu

- name: Ensure aptidude packages is installed
  action: apt name=aptitude state=installed update_cache=yes
  when: is_debian_or_ubuntu
  with_items:
    - aptitude
  environment:
    http_proxy: http://cloud-proxy:3128
    https_proxy: http://cloud-proxy:3128

