---
- name: insert PPA key
  remote_user: ubuntu
  sudo: yes
  sudo_user: root
  when: is_debian_or_ubuntu
  shell: /usr/bin/apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  environment:
    http_proxy: http://cloud-proxy:3128
    https_proxy: http://cloud-proxy:3128


- name: insert PPA sources.list
  remote_user: ubuntu
  sudo: yes
  sudo_user: root
  when: is_debian_or_ubuntu
  apt_repository: state=present update_cache=yes repo='deb https://get.docker.io/ubuntu docker main'
  environment:
    http_proxy: http://cloud-proxy:3128
    https_proxy: http://cloud-proxy:3128

- name: apt update
  apt: update_cache=yes
  remote_user: ubuntu
  sudo: yes
  sudo_user: root
  when: is_debian_or_ubuntu
  environment:
    http_proxy: http://cloud-proxy:3128
    https_proxy: http://cloud-proxy:3128


- name: Check if `docker` PPA package is installed
  apt: name={{item}} state=latest
  remote_user: ubuntu
  sudo: yes
  sudo_user: root
  with_items:
    - lxc-docker
  when: is_debian_or_ubuntu
  environment:
    http_proxy: http://cloud-proxy:3128
    https_proxy: http://cloud-proxy:3128


- name: place proxy export in docker
  lineinfile: dest="/etc/default/docker"  line="export http_proxy=http://cloud-proxy:3128; export https_proxy=http://cloud-proxy:3128" owner=root
  remote_user: ubuntu
  sudo: yes
  sudo_user: root

- name: chgrp of /var/run/docker.sock
  file: path=/var/run/docker.sock group=docker
  remote_user: ubuntu
  sudo: yes
  sudo_user: root

- name: restart docker
  service: name=docker state=restarted enabled=yes
  remote_user: ubuntu
  sudo: yes
  sudo_user: root
  
- name: add user ubuntu to group docker
  user: name=ubuntu state=present groups=docker append=yes
  remote_user: ubuntu
  sudo: yes
  sudo_user: root
