---
- name: set soft ulimit nofile to 100000
  lineinfile: dest="/etc/security/limits.conf" line="*\tsoft\tnofile\t100000" owner=root
  remote_user: ubuntu
  sudo: yes
  sudo_user: root

- name: set hard ulimit nofile to 100000
  lineinfile: dest="/etc/security/limits.conf" line="*\thard\tnofile\t100000" owner=root
  remote_user: ubuntu
  sudo: yes
  sudo_user: root

- name: add ${HOME}/.local/bin to $PATH
  lineinfile: dest="/home/ubuntu/.bashrc" line="PATH=${HOME}/.local/bin:$PATH"
  remote_user: ubuntu

- name: python3 as default virtualenvwrapper python
  lineinfile: dest="/home/ubuntu/.bashrc" line="export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3"
  remote_user: ubuntu

- name: source virtualenvwrapper.sh
  lineinfile: dest="/home/ubuntu/.bashrc" line="source ${HOME}/.local/bin/virtualenvwrapper.sh"
  remote_user: ubuntu